
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'Azuredevops-demo'
    command: 'login'
- task: Docker@2
  inputs:
    containerRegistry: 'Azuredevops-demo'
    repository: 'logstash'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
