
trigger:
- feature

pool:
  vmImage: ubuntu-latest

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'Azuredevops-demo'
    command: 'login'
- task: Docker@2
  inputs:
    containerRegistry: 'Azuredevops-demo'
    repository: 'logstash'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    arguments: '--build-arg LOGSTASH_PLUGINS=microsoft-logstash-output-azure-loganalytics'
- task: Docker@2
  inputs:
    containerRegistry: 'Azuredevops-demo'
    repository: 'logstash'
    command: 'Push'
    Dockerfile: '**/Dockerfile'
